version: '3.8'

services:
  flagd:
    build: .
    container_name: flagd
    ports:
      - "8013:8013"
#    volumes:
#      - ./:/app/
    command: ["start", "--uri", "file:/app/demo.flagd.json"]
#    command: ["start", "--uri", "https://raw.githubusercontent.com/sujeet-kumar-lab49/open-feature-test/main/flagd/demo.flagd.json"]


#volumes:
#  flagd-config:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: C:/Users/sujeet.kumar/D-Drive/D/OpenFeature/open-feature-test/flagd