apiVersion: v1
kind: ConfigMap
metadata:
  name: flagd-config
  namespace: default
data:
  flagd-config.yaml: |
    # Your configuration settings for flagd
    exampleFlag: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flagd
  template:
    metadata:
      labels:
        app: flagd
    spec:
      containers:
        - name: flagd
          image: your-registry/flagd:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/flagd
              subPath: flagd-config.yaml
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: flagd-config
---
apiVersion: v1
kind: Service
metadata:
  name: flagd-service
  namespace: default
spec:
  selector:
    app: flagd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP