apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-test
  template:
    metadata:
      labels:
        app: feature-test
    spec:
      containers:
        - name: feature-test
          image: lab49registry24.azurecr.io/feature-test:latest
          ports:
            - containerPort: 8015
          volumeMounts:
            - name: feature-test-config
              mountPath: /app/feature.json
              subPath: feature.json
      volumes:
        - name: feature-test-config
          configMap:
            name: feature-test-config
---
apiVersion: v1
kind: Service
metadata:
  name: feature-test
spec:
  selector:
    app: feature-test
  ports:
    - protocol: TCP
      port: 8015
      targetPort: 8015
  type: LoadBalancer  # Use NodePort or ClusterIP if you don't need an external load balancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-test-config
data:
  feature.json: |
    {
      "dynamicId" : "1234",
      "dynamicName" : "name2"
    }